Algoritmo "Dimensões de um retângulo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 7/18/2020
Var
 base,altura,area:real


Inicio
   escreval("Escreva a base do retângulo")
   leia(base)
   escreval("Escreva a altura do retângulo")
   leia(altura)
   area <- base*altura
   escreval("A área do retângulo é:", area, "cm²")
   


Fimalgoritmo